version: '3.8'
services:
# BANCO DADOS PROPOSTA--------------------------------------------------------
  database-transacao:
    image: mariadb:latest
    profiles:
      - producao
      - desenvolvimento
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=transacao
      - MYSQL_PASSWORD=transacao
      - MYSQL_DATABASE=transacao
    ports:
      - 3306:3306
    volumes:
      - database-transacao-volume:/var/lib/mariadb
    networks:
      - transacao-network
# TRANSAÇÕES
  transacoes:
    image: zupacademy/transacoes
    profiles:
      - producao
      - desenvolvimento
    ports:
      - 8081:8081
    depends_on:
      - kafka
    environment:
      SERVER_PORT: 8081
      LOG_LEVEL: INFO
      KAFKA_HOST: "kafka:29092"
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces
    networks:
      - transacao-network
# ZOOKEEPER
  zookeeper:
    image: confluentinc/cp-zookeeper:5.2.1
    profiles:
      - producao
      - desenvolvimento
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
    networks:
      - transacao-network
# KAFKA
  kafka:
    image: confluentinc/cp-kafka:5.2.1
    profiles:
      - producao
      - desenvolvimento
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - transacao-network
# KEYCLOAK
  keycloak:
    image: jboss/keycloak:11.0.0
    profiles:
      - producao
      - desenvolvimento
    ports:
      - 8443:8443
      - 8083:8080
      - 9990:9990
    depends_on:
      - banco-dados-proposta
      - analise-financeira
      - contas
    environment:
      DB_VENDOR: mariadb
      DB_ADDR: database-transacao
      DB_PORT: 3306
      DB_DATABASE: transacao
      DB_USER: transacao
      DB_PASSWORD: transacao
      KEYCLOAK_USER: keycloak
      KEYCLOAK_PASSWORD: Pa55w0rd
      KEYCLOAK_ISSUER_URI: http://keycloak:8083/auth/realms/proposta
      KEYCLOAK_JWKS_URI: http://keycloak:8083/auth/realms/proposta/protocol/openid-connect/certs
    restart: on-failure
    networks:
      - transacao-network

volumes:
  database-transacao-volume:
    name: database-transacao-volume

networks:
  transacao-network:
    driver: bridge